readInterval: 60000 # seconds between state updates
keepTempInterval: 60000 # seconds
heating:
  lowThreshold: 0.3 # how many degrees C below desiredTemp to start heating
  highThreshold: 0.4 # how many degrees C over desiredTemp to stop heating
  maxTemp: 26 # not used yet
  minTemp: 14 # not used yet

  tempPrograms:
    daytime:
      temp: 20
      tempIfEmpty: 19 # temperature if nobody is at home
    daytimeEmpty:
      temp: 19
    night:
      temp: 18

  dayPrograms:
    workday:
      '0:00': daytime
      '0:30': night # starting from 00:30, the night program is active
      '8:00': daytimeEmpty
      '17:00': daytime # from 17:00 to 23:59
    weekend:
      '0:00': daytime
      '1:30': night
      '9:00': daytime

  weekProgram:
    1: workday # Monday
    2: workday # Tuesday
    3: workday # ...
    4: workday
    5: workday
    6: weekend # Saturday
    0: weekend # Sunday
